/**
 * 类型文档生成器
 * 自动生成 TypeScript 类型文档和使用示例
 */

import type {
  ComponentSize,
  ComponentStatus,
  PlacementType,
  TriggerType,
  ThemeMode,
  Option,
  TreeNode,
  TableColumn,
  FormField,
  FileItem,
  ThemeConfig
} from './utils'

/**
 * 类型文档生成器
 */
export class TypeDocsGenerator {
  /**
   * 生成完整的类型文档
   */
  static generateFullDocs(): string {
    const sections = [
      this.generateHeader(),
      this.generateBasicTypes(),
      this.generateComponentTypes(),
      this.generateDataStructureTypes(),
      this.generateThemeTypes(),
      this.generateUtilityTypes(),
      this.generateExamples(),
      this.generateBestPractices()
    ]

    return sections.join('\n\n')
  }

  /**
   * 生成文档头部
   */
  private static generateHeader(): string {
    return [
      '# Vue 组件库类型系统文档',
      '',
      '本文档详细描述了 Vue 组件库的完整类型系统，包括组件属性、事件、插槽等类型定义。',
      '',
      '## 目录',
      '',
      '- [基础类型](#基础类型)',
      '- [组件类型](#组件类型)',
      '- [数据结构类型](#数据结构类型)',
      '- [主题类型](#主题类型)',
      '- [工具类型](#工具类型)',
      '- [使用示例](#使用示例)',
      '- [最佳实践](#最佳实践)'
    ].join('\n')
  }

  /**
   * 生成基础类型文档
   */
  private static generateBasicTypes(): string {
    return [
      '## 基础类型',
      '',
      '### 组件尺寸类型',
      '',
      '```typescript',
      'type ComponentSize = "small" | "middle" | "large"',
      '```',
      '',
      '用于定义组件的尺寸大小。',
      '',
      '### 组件状态类型',
      '',
      '```typescript',
      'type ComponentStatus = "success" | "warning" | "error" | "info" | "default"',
      '```',
      '',
      '用于定义组件的状态类型，影响颜色和图标显示。',
      '',
      '### 位置类型',
      '',
      '```typescript',
      'type PlacementType =',
      '  | "top" | "topLeft" | "topRight"',
      '  | "bottom" | "bottomLeft" | "bottomRight"',
      '  | "left" | "leftTop" | "leftBottom"',
      '  | "right" | "rightTop" | "rightBottom"',
      '```',
      '',
      '用于定义弹出层、提示框等组件的显示位置。',
      '',
      '### 触发方式类型',
      '',
      '```typescript',
      'type TriggerType = "hover" | "click" | "focus" | "contextmenu"',
      '```',
      '',
      '用于定义组件的触发方式。',
      '',
      '### 主题模式类型',
      '',
      '```typescript',
      'type ThemeMode = "light" | "dark" | "auto"',
      '```',
      '',
      '用于定义主题模式，auto 表示跟随系统主题。'
    ].join('\n')
  }

  /**
   * 生成组件类型文档
   */
  private static generateComponentTypes(): string {
    return [
      '## 组件类型',
      '',
      '### Modal 组件类型',
      '',
      '```typescript',
      'interface ModalProps extends AntModalProps {',
      '  size?: "small" | "default" | "large" | "fullscreen"',
      '  draggable?: boolean',
      '  resizable?: boolean',
      '  minWidth?: number',
      '  minHeight?: number',
      '  maxWidth?: number',
      '  maxHeight?: number',
      '  keepRatio?: boolean',
      '}',
      '```',
      '',
      '继承 Ant Design Vue Modal 的所有属性，并扩展了尺寸、拖拽、调整大小等功能。',
      '',
      '### Table 组件类型',
      '',
      '```typescript',
      'interface TableProps<T = any> extends AntTableProps<T> {',
      '  virtual?: boolean',
      '  exportable?: boolean',
      '  searchable?: boolean',
      '  columnSettings?: boolean',
      '  autoHeight?: boolean',
      '}',
      '```',
      '',
      '继承 Ant Design Vue Table 的所有属性，并扩展了虚拟滚动、导出、搜索等功能。',
      '',
      '### Form 组件类型',
      '',
      '```typescript',
      'interface FormProps extends AntFormProps {',
      '  columns?: number',
      '  collapsed?: boolean',
      '  autoSubmit?: boolean',
      '  fields?: FormField[]',
      '}',
      '```',
      '',
      '继承 Ant Design Vue Form 的所有属性，并扩展了多列布局、折叠、自动提交等功能。',
      '',
      '### Upload 组件类型',
      '',
      '```typescript',
      'interface FileUploadProps extends AntUploadProps {',
      '  dragUpload?: boolean',
      '  pasteUpload?: boolean',
      '  cameraUpload?: boolean',
      '  imagePreview?: boolean',
      '  imageCrop?: boolean',
      '  chunkUpload?: boolean',
      '  validation?: FileValidationRule',
      '}',
      '```',
      '',
      '继承 Ant Design Vue Upload 的所有属性，并扩展了拖拽上传、粘贴上传、图片预览等功能。'
    ].join('\n')
  }

  /**
   * 生成数据结构类型文档
   */
  private static generateDataStructureTypes(): string {
    return [
      '## 数据结构类型',
      '',
      '### 选项类型',
      '',
      '```typescript',
      'interface Option<T = any> {',
      '  label: string',
      '  value: T',
      '  disabled?: boolean',
      '  children?: Option<T>[]',
      '  [key: string]: any',
      '}',
      '```',
      '',
      '用于 Select、Cascader 等选择类组件的选项数据结构。',
      '',
      '### 树形数据类型',
      '',
      '```typescript',
      'interface TreeNode<T = any> {',
      '  key: string | number',
      '  title: string',
      '  value?: T',
      '  disabled?: boolean',
      '  children?: TreeNode<T>[]',
      '  [key: string]: any',
      '}',
      '```',
      '',
      '用于 Tree、TreeSelect 等树形组件的数据结构。',
      '',
      '### 表格列类型',
      '',
      '```typescript',
      'interface TableColumn<T = any> {',
      '  key: string',
      '  title: string',
      '  dataIndex?: string',
      '  width?: number | string',
      '  fixed?: "left" | "right"',
      '  sorter?: boolean | ((a: T, b: T) => number)',
      '  filters?: { text: string; value: any }[]',
      '  render?: (value: any, record: T, index: number) => SlotContent',
      '  [key: string]: any',
      '}',
      '```',
      '',
      '用于 Table 组件的列配置。',
      '',
      '### 表单字段类型',
      '',
      '```typescript',
      'interface FormField {',
      '  name: string',
      '  label: string',
      '  type: string',
      '  required?: boolean',
      '  rules?: ValidationRule[]',
      '  props?: Record<string, any>',
      '  [key: string]: any',
      '}',
      '```',
      '',
      '用于动态表单的字段配置。',
      '',
      '### 文件类型',
      '',
      '```typescript',
      'interface FileItem {',
      '  uid: string',
      '  name: string',
      '  status: "uploading" | "done" | "error" | "removed"',
      '  url?: string',
      '  thumbUrl?: string',
      '  size?: number',
      '  type?: string',
      '  [key: string]: any',
      '}',
      '```',
      '',
      '用于 Upload 组件的文件数据结构。'
    ].join('\n')
  }

  /**
   * 生成主题类型文档
   */
  private static generateThemeTypes(): string {
    return [
      '## 主题类型',
      '',
      '### 主题令牌类型',
      '',
      '```typescript',
      'interface ThemeToken {',
      '  colorPrimary?: string',
      '  colorSuccess?: string',
      '  colorWarning?: string',
      '  colorError?: string',
      '  colorInfo?: string',
      '  colorText?: string',
      '  colorBgBase?: string',
      '  borderRadius?: number',
      '  fontSize?: number',
      '  fontFamily?: string',
      '  [key: string]: any',
      '}',
      '```',
      '',
      '用于定义主题的基础设计令牌。',
      '',
      '### 组件主题类型',
      '',
      '```typescript',
      'interface ComponentTheme {',
      '  [componentName: string]: Record<string, any>',
      '}',
      '```',
      '',
      '用于定义各个组件的主题配置。',
      '',
      '### 完整主题配置类型',
      '',
      '```typescript',
      'interface ThemeConfig {',
      '  token?: ThemeToken',
      '  components?: ComponentTheme',
      '  algorithm?: any',
      '  [key: string]: any',
      '}',
      '```',
      '',
      '完整的主题配置，包含令牌、组件主题和算法。'
    ].join('\n')
  }

  /**
   * 生成工具类型文档
   */
  private static generateUtilityTypes(): string {
    return [
      '## 工具类型',
      '',
      '### 组件属性提取工具',
      '',
      '```typescript',
      'type ExtractComponentProps<T> = T extends DefineComponent<infer P, any, any, any, any, any, any, any>',
      '  ? P',
      '  : never',
      '```',
      '',
      '从组件定义中提取属性类型。',
      '',
      '### Ant Design Vue 属性继承工具',
      '',
      '```typescript',
      'type InheritAntdProps<T> = T & {',
      '  [K in keyof T]: T[K]',
      '}',
      '```',
      '',
      '继承 Ant Design Vue 组件的所有属性。',
      '',
      '### 扩展组件属性工具',
      '',
      '```typescript',
      'type ExtendComponentProps<Base, Extension> = Base & Extension & {',
      '  [K in keyof Base]: K extends keyof Extension ? Extension[K] : Base[K]',
      '}',
      '```',
      '',
      '扩展组件属性，确保类型安全。',
      '',
      '### 深度只读工具',
      '',
      '```typescript',
      'type DeepReadonly<T> = {',
      '  readonly [P in keyof T]: T[P] extends object ? DeepReadonly<T[P]> : T[P]',
      '}',
      '```',
      '',
      '将对象的所有属性（包括嵌套属性）设为只读。',
      '',
      '### 可选属性工具',
      '',
      '```typescript',
      'type OptionalProps<T, K extends keyof T> = Omit<T, K> & Partial<Pick<T, K>>',
      '```',
      '',
      '将指定属性设为可选。',
      '',
      '### 必需属性工具',
      '',
      '```typescript',
      'type RequiredProps<T, K extends keyof T> = T & Required<Pick<T, K>>',
      '```',
      '',
      '将指定属性设为必需。'
    ].join('\n')
  }

  /**
   * 生成使用示例文档
   */
  private static generateExamples(): string {
    return [
      '## 使用示例',
      '',
      '### 基础组件使用',
      '',
      '```vue',
      '<template>',
      '  <CustomModal',
      '    v-model:open="visible"',
      '    title="示例弹窗"',
      '    size="large"',
      '    draggable',
      '    resizable',
      '    @ok="handleOk"',
      '  >',
      '    <p>弹窗内容</p>',
      '  </CustomModal>',
      '</template>',
      '',
      '<script setup lang="ts">',
      'import { ref } from "vue"',
      'import type { ModalProps } from "vue-component-library"',
      '',
      'const visible = ref(false)',
      '',
      'const handleOk = () => {',
      '  visible.value = false',
      '}',
      '</script>',
      '```',
      '',
      '### 类型安全的组件属性',
      '',
      '```typescript',
      'import type { TableColumn, TableProps } from "vue-component-library"',
      '',
      'interface User {',
      '  id: number',
      '  name: string',
      '  email: string',
      '  status: ComponentStatus',
      '}',
      '',
      'const columns: TableColumn<User>[] = [',
      '  {',
      '    key: "name",',
      '    title: "姓名",',
      '    dataIndex: "name"',
      '  },',
      '  {',
      '    key: "email",',
      '    title: "邮箱",',
      '    dataIndex: "email"',
      '  },',
      '  {',
      '    key: "status",',
      '    title: "状态",',
      '    dataIndex: "status",',
      '    render: (status: ComponentStatus) => {',
      '      return <Tag color={getStatusColor(status)}>{status}</Tag>',
      '    }',
      '  }',
      ']',
      '',
      'const tableProps: TableProps<User> = {',
      '  columns,',
      '  dataSource: users,',
      '  virtual: true,',
      '  exportable: true',
      '}',
      '```',
      '',
      '### 主题配置示例',
      '',
      '```typescript',
      'import type { ThemeConfig } from "vue-component-library"',
      '',
      'const customTheme: ThemeConfig = {',
      '  token: {',
      '    colorPrimary: "#1890ff",',
      '    colorSuccess: "#52c41a",',
      '    borderRadius: 8,',
      '    fontSize: 14',
      '  },',
      '  components: {',
      '    CustomModal: {',
      '      dragHandleColor: "#1890ff",',
      '      resizeHandleColor: "#52c41a"',
      '    },',
      '    CustomTable: {',
      '      virtualScrollBarWidth: 8,',
      '      exportButtonColor: "#52c41a"',
      '    }',
      '  }',
      '}',
      '```',
      '',
      '### 类型验证示例',
      '',
      '```typescript',
      'import { TypeValidator, ComponentPropsValidator } from "vue-component-library"',
      '',
      '// 基础类型验证',
      'if (TypeValidator.isString(value)) {',
      '  // value 的类型被推断为 string',
      '  console.log(value.toUpperCase())',
      '}',
      '',
      '// 组件属性验证',
      'if (ComponentPropsValidator.validateSize(size)) {',
      '  // size 的类型被推断为 ComponentSize',
      '  console.log(`Size is ${size}`)',
      '}',
      '',
      '// 运行时类型检查',
      'const checkedValue = RuntimeTypeChecker.checkProp(',
      '  value,',
      '  TypeValidator.isNumber,',
      '  "count",',
      '  "MyComponent"',
      ')',
      '```'
    ].join('\n')
  }

  /**
   * 生成最佳实践文档
   */
  private static generateBestPractices(): string {
    return [
      '## 最佳实践',
      '',
      '### 1. 类型定义原则',
      '',
      '- **继承优于重写**：尽量继承 Ant Design Vue 的原生类型',
      '- **扩展而非替代**：在原有类型基础上扩展，不要完全替代',
      '- **类型安全**：确保所有属性都有正确的类型定义',
      '- **向后兼容**：新增类型不应破坏现有代码',
      '',
      '### 2. 组件开发规范',
      '',
      '```typescript',
      '// ✅ 推荐：继承并扩展',
      'interface CustomModalProps extends ModalProps {',
      '  customProp?: string',
      '}',
      '',
      '// ❌ 不推荐：完全重新定义',
      'interface CustomModalProps {',
      '  title?: string',
      '  visible?: boolean',
      '  customProp?: string',
      '}',
      '```',
      '',
      '### 3. 类型导入规范',
      '',
      '```typescript',
      '// ✅ 推荐：从统一入口导入',
      'import type { ModalProps, TableColumn } from "vue-component-library"',
      '',
      '// ❌ 不推荐：从内部路径导入',
      'import type { ModalProps } from "vue-component-library/src/components/Modal/types"',
      '```',
      '',
      '### 4. 泛型使用规范',
      '',
      '```typescript',
      '// ✅ 推荐：为数据类型提供泛型支持',
      'interface TableProps<T = any> {',
      '  dataSource?: T[]',
      '  columns?: TableColumn<T>[]',
      '}',
      '',
      '// 使用时指定具体类型',
      'const tableProps: TableProps<User> = {',
      '  dataSource: users,',
      '  columns: userColumns',
      '}',
      '```',
      '',
      '### 5. 类型验证规范',
      '',
      '```typescript',
      '// ✅ 推荐：在开发环境进行类型验证',
      'if (process.env.NODE_ENV === "development") {',
      '  RuntimeTypeChecker.checkProp(value, TypeValidator.isString, "title")',
      '}',
      '',
      '// ✅ 推荐：使用类型守卫',
      'function isValidOption(value: any): value is Option {',
      '  return TypeValidator.isObject(value) &&',
      '         "label" in value &&',
      '         "value" in value',
      '}',
      '```',
      '',
      '### 6. 文档维护规范',
      '',
      '- 每个新增类型都应该有对应的文档说明',
      '- 提供完整的使用示例',
      '- 标注类型的兼容性和变更历史',
      '- 定期更新类型文档，确保与代码同步',
      '',
      '### 7. 性能考虑',
      '',
      '- 避免过度复杂的类型定义',
      '- 合理使用条件类型和映射类型',
      '- 在生产环境中禁用运行时类型检查',
      '- 使用 TypeScript 的严格模式确保类型安全'
    ].join('\n')
  }

  /**
   * 生成 API 文档
   */
  static generateApiDocs(): string {
    return [
      '# API 文档',
      '',
      '## 类型验证器',
      '',
      '### TypeValidator',
      '',
      '基础类型检查器，提供常用的类型判断方法。',
      '',
      '#### 方法',
      '',
      '- `isString(value: any): value is string` - 检查是否为字符串',
      '- `isNumber(value: any): value is number` - 检查是否为数字',
      '- `isBoolean(value: any): value is boolean` - 检查是否为布尔值',
      '- `isFunction(value: any): value is Function` - 检查是否为函数',
      '- `isObject(value: any): value is object` - 检查是否为对象',
      '- `isArray(value: any): value is any[]` - 检查是否为数组',
      '- `isEmpty(value: any): boolean` - 检查是否为空值',
      '',
      '### ComponentPropsValidator',
      '',
      '组件属性验证器，提供组件相关的类型验证。',
      '',
      '#### 方法',
      '',
      '- `validateSize(size: any): size is ComponentSize` - 验证组件尺寸',
      '- `validateStatus(status: any): status is ComponentStatus` - 验证组件状态',
      '- `validatePlacement(placement: any): placement is PlacementType` - 验证位置类型',
      '- `validateColor(color: any): boolean` - 验证颜色值',
      '- `validateUrl(url: any): boolean` - 验证 URL',
      '',
      '### DataStructureValidator',
      '',
      '数据结构验证器，提供复杂数据结构的验证。',
      '',
      '#### 方法',
      '',
      '- `validateOptions(options: any): options is Option[]` - 验证选项数组',
      '- `validateTreeData(data: any): data is TreeNode[]` - 验证树形数据',
      '- `validateTableColumns(columns: any): columns is TableColumn[]` - 验证表格列配置',
      '',
      '### RuntimeTypeChecker',
      '',
      '运行时类型检查器，提供开发时的类型验证。',
      '',
      '#### 方法',
      '',
      '- `checkProp<T>(value: any, validator: (value: any) => value is T, propName: string, componentName?: string): T` - 检查属性类型',
      '- `getErrors(): ValidationError[]` - 获取验证错误',
      '- `clearErrors(): void` - 清除验证错误',
      '- `hasErrors(): boolean` - 检查是否有验证错误'
    ].join('\n')
  }

  /**
   * 生成迁移指南
   */
  static generateMigrationGuide(): string {
    return [
      '# 类型系统迁移指南',
      '',
      '## 从 v1.x 迁移到 v2.x',
      '',
      '### 主要变化',
      '',
      '1. **类型命名规范化**',
      '   - 所有组件类型都以 `Props` 结尾',
      '   - 事件类型都以 `Emits` 结尾',
      '   - 插槽类型都以 `Slots` 结尾',
      '',
      '2. **泛型支持增强**',
      '   - Table、Select 等组件增加了泛型支持',
      '   - 提供更好的类型推断',
      '',
      '3. **工具类型扩展**',
      '   - 新增多个类型工具函数',
      '   - 提供更强大的类型操作能力',
      '',
      '### 迁移步骤',
      '',
      '#### 1. 更新类型导入',
      '',
      '**旧版本：**',
      '```typescript',
      'import { ModalConfig, TableConfig } from "vue-component-library"',
      '```',
      '',
      '**新版本：**',
      '```typescript',
      'import type { ModalProps, TableProps } from "vue-component-library"',
      '```',
      '',
      '#### 2. 更新组件属性定义',
      '',
      '**旧版本：**',
      '```typescript',
      'const modalConfig: ModalConfig = {',
      '  title: "标题",',
      '  visible: true',
      '}',
      '```',
      '',
      '**新版本：**',
      '```typescript',
      'const modalProps: ModalProps = {',
      '  title: "标题",',
      '  open: true',
      '}',
      '```',
      '',
      '#### 3. 使用泛型类型',
      '',
      '**旧版本：**',
      '```typescript',
      'const columns: TableColumn[] = [...]',
      '```',
      '',
      '**新版本：**',
      '```typescript',
      'interface User {',
      '  id: number',
      '  name: string',
      '}',
      '',
      'const columns: TableColumn<User>[] = [...]',
      '```',
      '',
      '### 兼容性说明',
      '',
      '- ✅ 大部分类型保持向后兼容',
      '- ⚠️ 部分类型名称有变化，需要更新导入',
      '- ❌ 一些废弃的类型已被移除',
      '',
      '### 自动迁移工具',
      '',
      '我们提供了自动迁移工具帮助您快速迁移：',
      '',
      '```bash',
      'npx vue-component-library migrate-types',
      '```'
    ].join('\n')
  }
}

/**
 * 生成完整的类型文档
 */
export function generateTypeDocs(): {
  full: string
  api: string
  migration: string
} {
  return {
    full: TypeDocsGenerator.generateFullDocs(),
    api: TypeDocsGenerator.generateApiDocs(),
    migration: TypeDocsGenerator.generateMigrationGuide()
  }
}

/**
 * 导出类型文档到文件
 */
export function exportTypeDocsToFiles(): void {
  const docs = generateTypeDocs()
  
  // 在实际项目中，这里应该写入文件系统
  console.log('Full Type Docs:', docs.full)
  console.log('API Docs:', docs.api)
  console.log('Migration Guide:', docs.migration)
}